### ISSUE TITLE
Invisible Obstruction / Faulty Collision Detection.

### ISSUE THREAD

**Issue by Drenai13** [ashpemb/TGPSEM2#26]
**Reproduction:**
-Access the second level.
-Move along the positive X axis towards the right hand side of the second level.
-Change gravity and continue to move along the positive X axis whilst the player avatar is also moving up the positive Y axis.

**Consequences:**
-Player avatar slides against the wall on the right hand side and whilst the gravity is being changed, the avatar gets stuck on what appears to be a invisible platform.

**Occurrence:**
-100% of the time on the HTC Nexus Tablet & PC.

![image](https://cloud.githubusercontent.com/assets/15687435/14314216/dbebce5c-fbed-11e5-93bd-07b3e15b37fa.png)

**Comment by Malcom-Nubbins** [comment]
**Possible/Likely cause:**

As seen in that screenshot, the players sprite is halfway in the wall. As a result, its hitbox is touching the platform at its feet (to the right of it).
Likely an issue with the wall collisions not properly moving the player away from it.

**Comment by Flave229** [comment]
**Potential Solution:**
Because of collision issues in the past, the player uses a slightly smaller bounding box to collide. Perhaps use the full bounding box for walls, but the shaved bounding box for platforms. This should cause the wall to push the player far enough away from a platform to avoid this issue.
