### ISSUE TITLE
Stepping up objects that are taller than the characters height

### ISSUE THREAD

**Issue by kieran154** [ashpemb/TGPSEM2#37]
Reproduce
- Level 2
- Walk right along bottom platform and activate far right button
- Switch gravity to get to the top platform
- Switch gravity to normal
- Fall down to the barrier and then step back up to the platform

Consequences
- Could be abused in other situations

Percentage
- 100%

Platform
HTC Nexus & PC

![d9e20509701ed69b0eb8bd788de8681d](https://cloud.githubusercontent.com/assets/15891283/14326490/257b71d4-fc26-11e5-9313-659bd44d11ce.gif)

**Comment by Flave229** [comment]
Nice spot! This is due to the top of the player colliding with the platform still, and it attempts to correct the player position to ensure it doesn't fall "below" the platform. This can obviously be abused, as you have identified. 

**Solution:**
Recode the players bounding box to only do collision correction code on the players legs, rather than the entire sprite.
