### ISSUE TITLE
Level 4 can be completed very easily

### ISSUE THREAD

**Issue by BartoszGrabowski** [ashpemb/TGPSEM2#57]
**Reproduce:** Start level4, move player close to the wall on left, invert the gravity and player will stop on the wall above and be able to get to exit doors.
**Consequence:** level can be completed in couple seconds
**Device:** PC windows 8.1
![husky2](https://cloud.githubusercontent.com/assets/15784140/14587634/f4e2728a-04ad-11e6-9262-e0754d47bb47.png)

**Comment by Flave229** [comment]
This is a known issue that is present because the level is not yet complete, as its primary function was to provide a difficult puzzle implementing all mechanics. However, it will need fixing in the final version.

@JamesEdgerton1995 I am adding you to this issue as you are in charge of the level design.

**Comment by JamesEdgerton1995** [comment]
![level 4](https://cloud.githubusercontent.com/assets/15675235/14671668/f8c573f4-06ea-11e6-8455-5943c2b6128c.png) (Showing Changes that were made) Wall added to prevent player completing level straight away.
